# Generated by Django 3.0.7 on 2020-07-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_renameFields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
