# Generated by Django 3.1.7 on 2021-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_tutorprofile',
            field=models.BooleanField(default=False),
        ),
    ]
