# Generated by Django 3.0.7 on 2020-07-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0003_changeModuleFields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='fee',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='method',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person'), ('Both', 'Both')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='resume',
            field=models.FileField(default=None, upload_to='resumes'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='travel_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='zipcode',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
