# Generated by Django 3.0.7 on 2020-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_remodellingBlogToTutorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
