# Generated by Django 3.0.7 on 2020-07-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_tutorprofile_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='resume',
            field=models.FileField(blank=True, default=None, upload_to='resumes'),
        ),
    ]
