# Generated by Django 3.0.7 on 2020-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_allow_blank_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subject_details',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default=None)),
                ('tutor_profile', models.ManyToManyField(to='tutor.TutorProfile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
