# Generated by Django 3.0.7 on 2020-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_subject_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tutor_profile',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(to='tutor.Subject'),
        ),
    ]
